# fly.toml app configuration file generated for client-react on 2025-03-31T18:22:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'client-react'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
